FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=humble

SHELL ["/bin/bash", "-lc"]

RUN apt-get update && apt-get install -y \
    locales \
    curl \
    gnupg2 \
    lsb-release \
    software-properties-common \
    build-essential \
    cmake \
    git \
    libusb-1.0-0-dev \
    python3-pip \
    python3-dev \
    python3-argcomplete \
    python3-empy \
    python3-setuptools \
    python3-numpy \
    libboost-all-dev \
    libyaml-cpp-dev \
    libpcl-dev \
    && locale-gen en_US en_US.UTF-8 \
    && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
    | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" \
      > /etc/apt/sources.list.d/ros2.list

RUN apt-get update && apt-get install -y \
    ros-humble-ros-base \
    ros-humble-navigation2 \
    ros-humble-nav2-bringup \
    ros-humble-nav2-mppi-controller \
    ros-humble-nav2-velocity-smoother \
    ros-humble-rmw-cyclonedds-cpp \
    ros-humble-pcl-conversions \
    ros-humble-pcl-ros \
    ros-humble-rosidl-default-generators \
    python3-colcon-common-extensions \
    python3-vcstool \
    python3-rosdep \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
RUN git clone --depth 1 --branch releases/0.10.x https://github.com/eclipse-cyclonedds/cyclonedds.git \
    && cd cyclonedds \
    && mkdir build install \
    && cd build \
    && cmake .. -DCMAKE_INSTALL_PREFIX=../install \
    && cmake --build . --target install

ENV CYCLONEDDS_HOME=/opt/cyclonedds/install
ENV CMAKE_PREFIX_PATH=${CYCLONEDDS_HOME}:${CMAKE_PREFIX_PATH}

RUN pip3 install --no-cache-dir \
    numpy \
    cyclonedds==0.10.2 \
    pyrealsense2 \
    ecs-logging

COPY src/unitree_sdk2_python /opt/unitree_sdk2_python
RUN pip3 install --no-cache-dir --no-deps -e /opt/unitree_sdk2_python

COPY ros2_ws /workspace/ros2_ws

RUN mkdir -p /workspace/src \
    && ln -s /opt/unitree_sdk2_python /workspace/src/unitree_sdk2_python \
    && source /opt/ros/${ROS_DISTRO}/setup.bash \
    && cd /workspace/ros2_ws \
    && colcon build --symlink-install

WORKDIR /workspace/ros2_ws
CMD ["bash"]
